"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Modal } from "@/context/web3modal";
import { Provider } from "react-redux";
import { store } from "./../app/store/store";
import dotenv from "dotenv";
import Web3Provider from "@/components/providers/web3/page";

dotenv.config();

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "VisitorVault",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          <Web3Modal>
            <Provider store={store}>{children}</Provider>
          </Web3Modal>
        </Web3Provider>
      </body>
    </html>
  );
}
