"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Modal } from "@/context/web3modal";
import { Provider } from "react-redux";
import { store } from "./../app/store/store";
import { useEffect, useState } from "react";
import Loader from "@/components/loader/page";
import dotenv from "dotenv";

dotenv.config();

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "VisitorVault",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Modal>
          <Provider store={store}>{loading ? <Loader /> : children}</Provider>
        </Web3Modal>
      </body>
    </html>
  );
}
